### ISSUE TITLE
Lenna

### ISSUE THREAD

**Issue by smopucilowski** [cryptarch/workshop-images#1]
All workshops dealing with images should have the standard test image:

https://en.wikipedia.org/wiki/Lenna

**Comment by cryptarch** [comment]
Thanks for the suggestion; I hadn't heard of Lenna before :)

Although I appreciate the historical and humorous sentiment behind the suggestion, I think I should decline to include it for the moment. The possible offence caused by its controversial origins would be counter-productive, and would reflect poorly both on workshop instructors and on the organisations the instructors represent.

**Comment by shreyax** [comment]
saba, check your email! :'(
